version: '3.7'

services:
  level1:
    container_name: level1
    build:
      context: ./Levels/Level1
      dockerfile: Dockerfile
    image: level1
    ports:
      - "3001:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
  level2:
    container_name: level2
    build:
      context: ./Levels/Level2
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
  level3:
    container_name: level3
    build:
      context: ./Levels/Level3
      dockerfile: Dockerfile
    ports:
      - "3003:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
  level4:
    container_name: level4
    build:
      context: ./Levels/Level4
      dockerfile: Dockerfile
    ports:
      - "3004:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "host.docker.internal:host-gateway"      
  backend:
    container_name: backend
    build:
      context: ./dotnetBackend
      dockerfile: Dockerfile
    ports:
      - "5000:80"  
  frontend:
    container_name: frontend
    build:
      context: ./XSS-Platform
      dockerfile: Dockerfile
    ports:
      - "4200:80"  
    