version: '3.7'

services:
  level1:
    container_name: level3
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/local/app'
      - '/usr/local/app/node_modules'
    ports:
      - 3003:80
    environment:
      - CHOKIDAR_USEPOLLING=true