version: '3.7'

services:
  level4:
    container_name: level4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3004:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "host.docker.internal:host-gateway"