version: '3.7'

services:
  level1:
    container_name: level1
    build:
      context: .
      dockerfile: Dockerfile
    image: level1
    volumes:
      - '.:/usr/local/app'
      - '/usr/local/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "host.docker.internal:host-gateway"