version: '3.7'

services:
  level2:
    container_name: level2
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    extra_hosts:
      - "host.docker.internal:host-gateway"