version: '3.7'

services:
  level2:
    container_name: level2
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3002:3000
    environment:
      - CHOKIDAR_USEPOLLING=true